validate file exists and commented function to free memory

diff --git a/jaaa b/jaaa
--- a/jaaa
+++ b/jaaa
@@ -1,5 +1,20 @@
 #!/bin/bash
 
+file_exists() {
+	if [ $1 -eq 2 ]
+	then
+		file_name=$3
+	else
+		file_name=$2
+	fi
+
+	if [ ! -f $file_name ]
+	then
+		echo "Error: file '${file_name}' doesn't exist"
+		exit 1
+	fi
+}
+
 validate_extension() {
 	file_path=$1
 	file_extension="${file_path##*.}"
@@ -78,18 +93,20 @@ generate_java_byte_code() {
 
 language="C"
 
+file_exists $# $1 $2
+
 validate_arguments $# $1 $2
 
 if [ $? -eq 0 ]
 then
 	if [ $language == "C" ]
 	then
-		echo "compiling to generate c executable code"
+		echo "Compiling to generate c executable code"
 		make_files
 		generate_c_code $1
 
 	else
-		echo "compiling to generate bytecode"
+		echo "Compiling to generate bytecode"
 		make_files
 		generate_java_byte_code $2
 	fi
